spring:
  cloud:
    config:
      server:
        git:
          url: https://github.com/zachsnachs/configuration-files.git
          username: ${git.username}$
          password: ${git.password}$
          default-label: master
server:
  port: 8071
